### ISSUE TITLE
Multitouch potentially working

### ISSUE THREAD

**Issue by FrauH0lle** [matthewwardrop/linux-surfacepro3#1]
Thank you very much for your effort providing a working PKGBUILD!!
Just wanted to comment about the new multitouch functionalitiy: according to https://github.com/nuclearsandwich/surface3-archlinux/issues/4 the full functionality can be unlocked by creating a file in Xorg.conf.d containing

Section "InputClass"
        Identifier "Default clickpad buttons"
        MatchDriver "synaptics"
        Option "ClickPad" "true"
        Option "SoftButtonAreas" "50% 0 82% 0 0 0 0 0"
        Option "SecondarySoftButtonAreas" "58% 0 0 15% 42% 58% 0 15%"
EndSection

For me, this works flawless.

**Comment by colorprint** [comment]
Yes, with synaptics drivers and ClickPad option enabled right click works fine.

**Comment by matthewwardrop** [comment]
I've added the Xorg configuration to the linux package (yeah... not totally clean... hopefully this won't be necessary in the future). The multitouch patch is now applied by default.

Thanks for reporting this :).
