### ISSUE TITLE
sha256sum checksum failure.

### ISSUE THREAD

**Issue by en4ble** [matthewwardrop/linux-surfacepro3#10]
fix: 

```
pkgbuild -g
```

Copy output in PKGBUILD and overwrite the 

```
sha256sums=()
```

in there.

**Comment by matthewwardrop** [comment]
Hi en4ble,

Just saw this. I'm pretty sure this is working in the current master. Reopen if it is not :).

Thanks!

**Comment by en4ble** [comment]
Hey matthewwardrop,

thanks for the update, no checksum failure so far. Upgrading my kernel now, thank you and keep up the good work!

**Comment by matthewwardrop** [comment]
Excellent. You will probably need to reclone this repo when you next want to use it. I've suppressed many commits, and rebased dramatically, in order to allow for simple synchronisation with the aur website. (Or just use AUR) ;).
