### ISSUE TITLE
Touchpad not working

### ISSUE THREAD

**Issue by pacomaro** [matthewwardrop/linux-surfacepro3#12]
Hi there!
The touchpad doesn't seem to be working even after the kernel patch.
It only works if I log in to gnome on wayland but when I do that, the pen doesn't work.

**Comment by matthewwardrop** [comment]
Ah... sorry! I didn't see this here. As per my comment here: https://github.com/nuclearsandwich/surface3-archlinux/issues/17 , the solution is installing: xf86-input-libinput .
