### ISSUE TITLE
Touchscreen fixes

### ISSUE THREAD

**Issue by frebib** [matthewwardrop/linux-surfacepro3#14]
Hi there,
From what others have been saying, the following patches fix the touchscreen from suddenly stopping working in 4.4 and I assume 4.3 too.
https://github.com/tiggerite/mint-17.3-for-surface-pro-3/blob/master/patches-4.4/HID-multitouch-Add-MT_QUIRK_NOT_SEEN_MEANS_UP-to-MT_.patch
https://github.com/tiggerite/mint-17.3-for-surface-pro-3/blob/master/patches-4.4/HID-multitouch-Ignore-invalid-reports.patch
They have already been included in the Fedora SP3 kernel and the kernel above, it seems good reports so far
I've personally not tried these patches as my surface is away for repair but is there a chance they can be included?
Thanks

**Comment by frebib** [comment]
Update: Compatible with 4.{3,4} according to the author.
Source: https://www.reddit.com/r/SurfaceLinux/comments/406z9n/how_well_does_arch_run_on_an_sp3/cyv5u54?context=3

**Comment by matthewwardrop** [comment]
Hi @frebib ,

Sorry about the delay. I didn't get any notifications, and don't check this very frequently. If I can get multitouch patches working again in 4.4, I'll include these too (though this has never actually been a problem for me).

Best,
M

**Comment by matthewwardrop** [comment]
These are now included, btw :). Thanks for pointing them out.
