### ISSUE TITLE
Type Cover 4 doesn't work

### ISSUE THREAD

**Issue by NickGeek** [matthewwardrop/linux-surfacepro3#15]
The type cover 4 (on my SP3) doesn't work with this kernel.

**Comment by frebib** [comment]
First off, are you talking about the newest type cover with the glass trackpad? This is the cover I have and it works fine for myself and just about everyone else using it.

And secondly, can you post the output of `uname -a`

**Comment by NickGeek** [comment]
Yup, that's the one.

My output:
`Linux nick-surface-linux 4.4.0-1-surfacepro3 #1 SMP PREEMPT Fri Jan 15 21:09:27 NZDT 2016 x86_64 GNU/Linux`

As you can see I am running this kernel from the AUR. My Type Cover 3 works perfectly (that's what I'm typing this on) except for multi-touch,  but the Type Cover 4 doesn't work at all for me.

**Comment by frebib** [comment]
Try updating the kernel to the most recent commit that reverts back to 4.3.3.

Multi touch is known to not work in 4.4 but maybe the newer TC4 hasn't been tested. It worked for me in 4.3.3 but I can't comment on the 4.4 version. My surface should be back in a couple of days so I can confirm then.

**Comment by NickGeek** [comment]
Just tested with the reverted 4.3 one. The TC4 works perfectly now with multi-touch. Thanks!
