### ISSUE TITLE
Cannot find wireless networks after update to 4.6.1

### ISSUE THREAD

**Issue by ianks** [matthewwardrop/linux-surfacepro3#16]
After installing the latest version (4.6.1), it seems that wifi is no longer working. Scanning for networks in wifi-menu shows no networks are available. I noticed there was a wifi patch, do I need to change anything in order to make this work properly?

**Comment by en4ble** [comment]
I noticed it sometimes when I turned it back on from hibernation. I think the wifi patch is already enabled in the kernel.. Luckily reboot doesn't take so long.

**Comment by ianks** [comment]
I experienced an issue with rfkill blocking the wifi module when running powertop --calibrate. It was fixed by running `rfkill unblock all`
