### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by matthewwardrop** [matthewwardrop/linux-surfacepro3#17]

**Comment by GrayHatter** [comment]
If you want more flexibility and ease of getting user support while still maintaining control. I suggest you transfer the repo from a personal account to a GitHub group. 

It'll allow you to create teams that you can allow to help, without actually giving anyone write permissions to the repo. So other people can help manage and get involved much easier.

**Comment by matthewwardrop** [comment]
@GrayHatter : I'm not sure there's enough demand for this repo to justify that... :).
