### ISSUE TITLE
Script not waiting for input

### ISSUE THREAD

**Issue by pahofmann** [matthewwardrop/linux-surfacepro3#2]
When installing from AUR the script does not wait for the input on the question if it should enable multiouch. It just continues with the script and multitouch is disabled when its done.

I edited the makepkg to just include the patch line (without user input), multitouch works fine now.

Also (optional) additional make flags via user prompt would be great, so you could add "-j3" for way faster compiling without editing the makepkg by hand.

**Comment by matthewwardrop** [comment]
Thanks for the feedback pahofmann. I didn't see this, so I apologise for the delay :).

Were you using `makepkg` directly? Or were  you using a manager like `packer`?

Regarding adding "-j3", I'm trying to stick as closely as possible to the official builds. Hard-cording -j3 would not be appropriate on a system that had 8 processors or indeed only 1. What you can do instead is run:

```
MAKE='make -j3' makepkg
```

Or:

```
export MAKE='make -j3'
makepkg
```

**Comment by matthewwardrop** [comment]
The latest head now no longer asks for user input; installing the multitouch patch by default with the Xorg configuration. That renders this issue no longer a problem (although I'm still curious about why it did not wait for input).

**Comment by pahofmann** [comment]
I was using a packagemanager (pacaur). I'm still wondering why it was not waiting for input, too.

**Comment by matthewwardrop** [comment]
Ah .. Managers like pacaur and packer steal input, I think. It's probably bad form to prompt during build anyway...
