### ISSUE TITLE
Battery

### ISSUE THREAD

**Issue by ianks** [matthewwardrop/linux-surfacepro3#3]
After compiling this kernel I noticed my battery always indicates 0% charge. Is there any other configuration I need to set to make it happy?

**Comment by pahofmann** [comment]
Works fine for me, without additional config.

**Comment by ianks** [comment]
Hmm. Can you quickly run thru your install process? You don't have to be super specific, just want to make sure I didn't miss anything obvious. Also, was your battery indicator working pre kernel patch? Mine was I think.

**Comment by pahofmann** [comment]
I had stock 3.19 Kernel without patches before, Battery indicator wasn't working there.
I just installed via AUR, depends on the packagemanager you use e.g. pacaur -S linux-surfacepro3.
Then remake your grubconfig with grub-mkconfig.

**Comment by ianks** [comment]
Got it fixed. Forgot to update my Gummiboot config :fearful:
