### ISSUE TITLE
Multitouch patches lead to Caps lock light not working

### ISSUE THREAD

**Issue by quininer** [matthewwardrop/linux-surfacepro3#4]
Before using the patch, Caps lock light are normal.
Found to be normal after the reboot using the official kernel, Caps lock lights work.

**Comment by matthewwardrop** [comment]
Yeah... that seems to be the case. If you build the kernel with "multitouch='n'", this issue should go away. However, I personally prefer having multitouch support... :).

I've added this trade-off to the notes in README.md.

**Comment by quininer** [comment]
I also like multitouch.
In fact, besides I found my SP3 search to 5G wifi.
The recent Linux 4 to come out, I hope more and more perfect. :)
