### ISSUE TITLE
install: target ‘/home/ianks/linux-surfacepro3/pkg/linux-surfacepro3/etc/X11/xorg.conf.d/’ is not a directory: No such file or directory

### ISSUE THREAD

**Issue by ianks** [matthewwardrop/linux-surfacepro3#5]
I get an error when compiling the kernel:

`install: target ‘/home/ianks/linux-surfacepro3/pkg/linux-surfacepro3/etc/X11/xorg.conf.d/’ is not a directory: No such file or directory`

Figured I would give a heads up :smile:

**Comment by matthewwardrop** [comment]
Thanks ianks. That's odd though, since install -D should create those directories. I'll see if I can't resolve it for the next update (to 4.0).

**Comment by ianks** [comment]
Awesome. I'll keep an eye out.

**Comment by ianks** [comment]
The only thing I did differently was to alias make to make -j4

**Comment by matthewwardrop** [comment]
Since I do that too, I don't think that should affect things; but thanks for giving me the context :).

btw, you can also do: 

```
export MAKE='make -j4'
```

That way you don't override make :).

**Comment by matthewwardrop** [comment]
According to the `install` docs, the -D option should "create all leading components of DEST except the last, then copy SOURCE to DEST". This worked for me on my system, and I'd like to debug this a bit first, before adding what ought to be "redundant" code.

I'm a bit surprised of the discrepancies, given that we both use Arch Linux in configuration close to stock.

Thanks for the patch though :). I'll gladly pull it in if it becomes necessary. Once 4.0 makes it to the main repository, I'll update my PKGBUILD and get you to test it on your machine.

**Comment by matthewwardrop** [comment]
Whoops. Turns out that the reason it worked for me and not for you was because I didn't push the latest changes in my local build folder. Sorry about that. Should work fine for you now.

Reopen this issue if you still experience problems.
