### ISSUE TITLE
USB not recognized on boot

### ISSUE THREAD

**Issue by ianks** [matthewwardrop/linux-surfacepro3#7]
When booting with this kernel, my USB keyboard is not automatically recognize; causing me to have to re-plug in my keyboard. There seems to be an issue with allocating space for the number of USB devices. I have confirmed this error does not occur with the standard arch kernel.

**Comment by matthewwardrop** [comment]
I can't reproduce that here. Does anyone else have this problem?

**Comment by matthewwardrop** [comment]
Do you still have this problem?

**Comment by ianks** [comment]
On and off. I will re-open if I find anymore information about this.
